### ISSUE TITLE
Animation problem from iPad Pro 1920 x 1080 .mov

### ISSUE THREAD

**Issue by mac4kent** [cgtinker/BlendArMocap#57] opened 2022-06-03 05:31 UTC
I do use ASL (Sign language) I am full deaf.
Blender any version still rigging cause nervous move itself. I am not anything nervous just very smooth.
Just use .mov and 1920 x 1080 60fps from iPad Pro and send to iMac

<img width="698" alt="image" src="https://user-images.githubusercontent.com/4253305/171792173-5b564c2b-5425-4315-addf-adb246e12115.png">

<img width="3200" alt="image" src="https://user-images.githubusercontent.com/4253305/171792324-4eae28ce-58b4-4467-9589-c63612aa8568.png">
[Kent deaf sign language Blender.zip](https://github.com/cgtinker/BlendArMocap/files/8829744/Kent.deaf.sign.language.Blender.zip)

**Comment by cgtinker** [comment] 2022-06-03 06:16
What's a nervous move?

**Comment by mac4kent** [comment] 2022-06-03 06:47
I have problem english text only.
My video is not nervous but Blender bone is nervous itself.
Blendarmocap is great I like. Many online they wants $$$ too many I not want to buy online. 
I found this here blendarmocap is great.

**Comment by cgtinker** [comment] 2022-06-03 07:11
Now I get it. There is jitter in the animation when using prerecorded videos.

Yes, this is the raw result. It's easy to clean it up in blender - just select the empties, go in the graph editor > keys > smooth keys.

I decided to not directly smooth it for more control.

Think it's in the dev readme also.

**Comment by mac4kent** [comment] 2022-06-03 07:13
Sure. My iPad Pro is very very much clear without jitter. my iMac doesn't have jitter camera too.
I not know "graph editor" can you show me screenshot?

**Comment by mac4kent** [comment] 2022-06-03 07:22
My video sign language a, b, c, d, e, f, g, h, i, j cause bone doesn't correct.
pose not work correct.
head is correct move.

**Comment by cgtinker** [comment] 2022-06-03 08:29
I don't really understand nervous. What's a nervous bone? Can you check if jitter is the issue or describe it better please

What's kind of incorrect move?

**Comment by cgtinker** [comment] 2022-06-03 08:50
> Sure. My iPad Pro is very very much clear without jitter. my iMac doesn't have jitter camera too.
> I not know "graph editor" can you show me screenshot?

This confused me - what's clear?

**Comment by mac4kent** [comment] 2022-06-03 13:14
See youtube: https://youtu.be/1TQ04Z8vMIc
First is ABC's hand is nervous.
Second is ABC's hand is no nervous.
Blender bone rigging is fail because of nervous bone itself.

My iPad camera is not jitter.
My iMac camera is not jitter.

- - - - - - - - - - - - - - - - - - - - - 

Youtube: https://youtu.be/TOd-RAVWuvA
There have no nervous my hand with white bone is no nervous then go click play I can tell there too much nervous itself (see youtube https://youtu.be/lGtceUjzF4A )

- - - - - - - - - - - - - - - - - - - - - 

Graph Editor see line is too much nervous see youtube https://youtu.be/geWbo6b_MrE 

- - - - - - - - - - - - - - - - - - - - - 

Graph Editor clean up from nervous line become no nervous (flat) see youtube: https://youtu.be/I39PSxXBu3Y

**Comment by cgtinker** [comment] 2022-06-03 16:03
jitter while detecting has to be expected. 
you can reduce it using the graph editor:

1. select all the empties in the hand collection
2. navigate to the graph editor, press _a_ to select all keyframes
3. navigate to _keys > smooth keys_ - you can use _smooth keys_ multiple time to reach the desired result

![smooth](https://user-images.githubusercontent.com/55130054/171902856-220ecd2e-14c1-42da-9eef-50f25a09bc2f.png)

**Comment by mac4kent** [comment] 2022-06-03 16:39
Oh I got it and still not good. I am show you other video to show you clear. ABC's is not good rigging
[ASL ABC into Blendre.zip](https://github.com/cgtinker/BlendArMocap/files/8834184/ASL.ABC.into.Blendre.zip)
 .

**Comment by mac4kent** [comment] 2022-06-05 14:37
Now did you get it?

**Comment by cgtinker** [comment] 2022-06-05 17:47
you should prefer to work with a video rather than just still images. this implementation delivers a bridge to use mediapipe within blender - you may have to adjust values depending on the input data. I'll present workflows in the future. this is not a bug or error, it's just the wrong workflow.

**Comment by mac4kent** [comment] 2022-06-05 17:56
What is workflow?

**Comment by mac4kent** [comment] 2022-06-05 17:57
adjust like 100,000,000,000 to fix take 5 years to perfect. too much work to do.

**Comment by mac4kent** [comment] 2022-06-05 17:59
Movie and Stream is still error with body post not work as well. I did test already also ABC hand still error (nervous) not matter stream and movie too.

**Comment by cgtinker** [comment] 2022-06-05 18:30
the blender version doesn't matter here. the add-on is an implementation of googles mediapipe.
https://google.github.io/mediapipe/

googles mediapipe provides different type of tracking types. blendarmocap delivers a bridge of the data to blender. 
1. create a video or use the webcam stream. preferably don't use just still images as movie input.
2. u may use the manipulation options to modify the data which are mentioned in the readme.
3. tracking data always contains jitter. therefore use the smoothing if necessary.


You are using a development build, which contains a readme, please read it. As there are neither visible bugs or issues with the program itself, I'll close this down. If this add-on doesn't satisfy your needs, I cannot help it.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Closed by cgtinker** 2022-06-05 18:30 UTC

**Comment by mac4kent** [comment] 2022-06-05 19:14
1. I already did video and movie I send to you. You did not look up .mov
2. modify data I don't know how to fix code.
3. Track data I don't know how.Smooth is not true because of sign language with ABC cause bone nervous itself. Body Pose not work I already told you. You did not check .mov.

**Comment by mac4kent** [comment] 2022-06-05 19:15
ASL "C" cause bone "B" not correct!

**Comment by cgtinker** [comment] 2022-06-05 19:58
I did watch your video, but I cannot really help you there. Mediapipe detection results aren't perfect, there is jitter, but that has to be expected when working with AR models. However, I told you to read the readme which is also included in the add-ons zip file: https://github.com/cgtinker/BlendArMocap/tree/development

In there is a section about "How to manipulate transfer results" and also a lot of useful information on how to use the add-on. I've seen the failure of the tracking on a sign - it can happen that the detection fails, working with the stream detection helps to figure out how the mediapipes detection behaves in different situations. To use the toolset properly there surely is a learning curve involved, also I'm planning to release more resources in the future, but I don't know how to help you with your issues.

I've seen you dropped in images in a video which resulted in weird results while the capture results with a real video looked as expected. To smooth it out, as mentioned in the readme, may offset the time and apply smoothing. To adjust finger angles on the rig use the custom data properties on the rigify bones mentioned in the "How to manipulate transfer results" section.

**Comment by mac4kent** [comment] 2022-06-05 20:24
Oh well look at Apple Developers.
I already "README" there is not match what sign language. I believe lot BUG!

**Comment by cgtinker** [comment] 2022-06-05 20:30
This application is not a sign language parser, this application has nothing to do with apple. It's an add-on for artist to use mediapipe as resource for character animation. The readme focusses on how to use the toolset. The provided information can also be applied on your use case.

**Comment by mac4kent** [comment] 2022-06-05 20:31
Sigh.
